# Generated by Django 4.2.2 on 2023-06-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=40)),
                ('Last_Name', models.CharField(max_length=40)),
                ('Email_Address', models.CharField(max_length=255)),
                ('Address', models.TextField()),
                ('Message', models.TextField()),
            ],
        ),
    ]
