# Generated by Django 4.2.2 on 2023-06-30 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0004_rename_address_message_full_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='Full_Address',
        ),
    ]
